<LoginScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: "20dp"
        spacing: "10dp"
        
        MDRectangleFlatButton:
            text: "Connect device"
            pos_hint: {"center_x": 0.5}
            on_release: root.generate_qr()
        Image:
            id: qr_code_image
            size_hint: None, None
            size: "350dp", "350dp"
            pos_hint: {"center_x": 0.5}
            fit_mode:"fill"

